# 리버스 프록시 설정을 위한 context path 설정 추가, 포트 변경
server:
  servlet:
    context-path: /api
  port: 8081

spring:
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
      platform: mysql
  profiles:
    active: ${profile}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#jwt - 이슈 발급자, 비밀키 설정
jwt:
  issuer: ssafying@ssafy.com
  secret_key: b210-ssafying-teamjejudo