spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafying?autoReconnect=true
    username: ssafy
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true